modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId       = "attackaura"
version     = "1.0.0"
displayName = "Attack Aura"
description = "Attacks nearby players while flying with elytra."

[[dependencies.attackaura]]
    modId        = "forge"
    mandatory    = true
    versionRange = "[36,)"
    ordering     = "NONE"
    side         = "BOTH"

[[dependencies.attackaura]]
    modId        = "minecraft"
    mandatory    = true
    versionRange = "[1.16.5,1.17)"
    ordering     = "NONE"
    side         = "BOTH"
